-- =========================================================
-- QUINDIOFLIX - ENTREGA 1
-- Script 01: Creacion de tablas, restricciones y comentarios
-- =========================================================

SET DEFINE ON;
SET SERVEROUTPUT ON;


PROMPT =====================================================
PROMPT LIMPIEZA PREVIA DE OBJETOS
PROMPT =====================================================

BEGIN EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW mv_popularidad_contenido'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW mv_ingresos_mensuales'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE reportes_contenido CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE favoritos CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE calificaciones CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE reproducciones CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE pagos CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE contenido_relacionado CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE episodios CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE temporadas CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE contenido_genero CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE contenido CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE generos CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE categorias CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE perfiles CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE usuario_rol_app CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE roles_app CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE usuarios CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE empleados CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE departamentos CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE planes CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT =====================================================
PROMPT TABLAS MAESTRAS
PROMPT =====================================================

CREATE TABLE planes (
    id_plan              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_plan          VARCHAR2(20)   NOT NULL,
    precio_mensual       NUMBER(10,2)   NOT NULL,
    max_pantallas        NUMBER(2)      NOT NULL,
    calidad_video        VARCHAR2(10)   NOT NULL,
    max_perfiles         NUMBER(2)      NOT NULL,
    descripcion          VARCHAR2(200),
    CONSTRAINT pk_planes PRIMARY KEY (id_plan),
    CONSTRAINT uq_planes_nombre UNIQUE (nombre_plan),
    CONSTRAINT ck_planes_nombre CHECK (nombre_plan IN ('BASICO', 'ESTANDAR', 'PREMIUM')),
    CONSTRAINT ck_planes_precio CHECK (precio_mensual > 0),
    CONSTRAINT ck_planes_pantallas CHECK (max_pantallas BETWEEN 1 AND 10),
    CONSTRAINT ck_planes_calidad CHECK (calidad_video IN ('SD', 'HD', '4K')),
    CONSTRAINT ck_planes_perfiles CHECK (max_perfiles BETWEEN 1 AND 10)
);

CREATE TABLE departamentos (
    id_departamento      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_departamento  VARCHAR2(40)   NOT NULL,
    descripcion          VARCHAR2(200),
    id_jefe              NUMBER,
    CONSTRAINT pk_departamentos PRIMARY KEY (id_departamento),
    CONSTRAINT uq_departamentos_nombre UNIQUE (nombre_departamento)
);

CREATE TABLE empleados (
    id_empleado          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_departamento      NUMBER         NOT NULL,
    supervisor_id        NUMBER,
    nombres              VARCHAR2(80)   NOT NULL,
    apellidos            VARCHAR2(80)   NOT NULL,
    correo               VARCHAR2(120)  NOT NULL,
    telefono             VARCHAR2(20),
    cargo                VARCHAR2(60)   NOT NULL,
    fecha_ingreso        DATE           NOT NULL,
    salario              NUMBER(12,2)   NOT NULL,
    estado_empleado      VARCHAR2(15)   DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT pk_empleados PRIMARY KEY (id_empleado),
    CONSTRAINT uq_empleados_correo UNIQUE (correo),
    CONSTRAINT fk_emp_departamento FOREIGN KEY (id_departamento) REFERENCES departamentos(id_departamento),
    CONSTRAINT fk_emp_supervisor FOREIGN KEY (supervisor_id) REFERENCES empleados(id_empleado),
    CONSTRAINT ck_emp_estado CHECK (estado_empleado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT ck_emp_salario CHECK (salario > 0)
);

ALTER TABLE departamentos
    ADD CONSTRAINT fk_dept_jefe
    FOREIGN KEY (id_jefe) REFERENCES empleados(id_empleado);

CREATE TABLE usuarios (
    id_usuario           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_plan_actual       NUMBER         NOT NULL,
    id_usuario_referidor NUMBER,
    nombres              VARCHAR2(80)   NOT NULL,
    apellidos            VARCHAR2(80)   NOT NULL,
    email                VARCHAR2(120)  NOT NULL,
    telefono             VARCHAR2(20),
    fecha_nacimiento     DATE           NOT NULL,
    ciudad               VARCHAR2(60)   NOT NULL,
    fecha_registro       DATE           DEFAULT TRUNC(SYSDATE) NOT NULL,
    fecha_ultimo_pago    DATE,
    fecha_vencimiento    DATE,
    estado_cuenta        VARCHAR2(15)   DEFAULT 'ACTIVO' NOT NULL,
    beneficio_referido   VARCHAR2(120),
    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuarios_email UNIQUE (email),
    CONSTRAINT fk_usr_plan FOREIGN KEY (id_plan_actual) REFERENCES planes(id_plan),
    CONSTRAINT fk_usr_referidor FOREIGN KEY (id_usuario_referidor) REFERENCES usuarios(id_usuario),
    CONSTRAINT ck_usr_estado CHECK (estado_cuenta IN ('ACTIVO', 'SUSPENDIDO', 'INACTIVO'))
);

CREATE TABLE roles_app (
    id_rol_app           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_rol           VARCHAR2(30)   NOT NULL,
    descripcion          VARCHAR2(200),
    CONSTRAINT pk_roles_app PRIMARY KEY (id_rol_app),
    CONSTRAINT uq_roles_app UNIQUE (nombre_rol)
);

CREATE TABLE usuario_rol_app (
    id_usuario           NUMBER NOT NULL,
    id_rol_app           NUMBER NOT NULL,
    fecha_asignacion     DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    CONSTRAINT pk_usuario_rol_app PRIMARY KEY (id_usuario, id_rol_app),
    CONSTRAINT fk_ura_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_ura_rol FOREIGN KEY (id_rol_app) REFERENCES roles_app(id_rol_app)
);

CREATE TABLE perfiles (
    id_perfil            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario           NUMBER         NOT NULL,
    nombre_perfil        VARCHAR2(60)   NOT NULL,
    avatar               VARCHAR2(120),
    tipo_perfil          VARCHAR2(10)   NOT NULL,
    fecha_creacion       DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    CONSTRAINT pk_perfiles PRIMARY KEY (id_perfil),
    CONSTRAINT uq_perfiles_usuario_nombre UNIQUE (id_usuario, nombre_perfil),
    CONSTRAINT fk_perfiles_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT ck_perfiles_tipo CHECK (tipo_perfil IN ('ADULTO', 'INFANTIL'))
);

CREATE TABLE categorias (
    id_categoria         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_categoria     VARCHAR2(30)   NOT NULL,
    descripcion          VARCHAR2(200),
    CONSTRAINT pk_categorias PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categorias_nombre UNIQUE (nombre_categoria)
);

CREATE TABLE generos (
    id_genero            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_genero        VARCHAR2(40)   NOT NULL,
    descripcion          VARCHAR2(200),
    CONSTRAINT pk_generos PRIMARY KEY (id_genero),
    CONSTRAINT uq_generos_nombre UNIQUE (nombre_genero)
);

CREATE TABLE contenido (
    id_contenido             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_categoria             NUMBER         NOT NULL,
    id_empleado_responsable  NUMBER         NOT NULL,
    titulo                   VARCHAR2(150)  NOT NULL,
    anio_lanzamiento         NUMBER(4)      NOT NULL,
    duracion_minutos         NUMBER(6)      NOT NULL,
    sinopsis                 VARCHAR2(1000),
    clasificacion_edad       VARCHAR2(5)    NOT NULL,
    fecha_agregado_catalogo  DATE           DEFAULT TRUNC(SYSDATE) NOT NULL,
    es_original              CHAR(1)        DEFAULT 'N' NOT NULL,
    popularidad              NUMBER(10)     DEFAULT 0 NOT NULL,
    estado_publicacion       VARCHAR2(15)   DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT pk_contenido PRIMARY KEY (id_contenido),
    CONSTRAINT fk_cont_categoria FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria),
    CONSTRAINT fk_cont_empleado FOREIGN KEY (id_empleado_responsable) REFERENCES empleados(id_empleado),
    CONSTRAINT ck_cont_anio CHECK (anio_lanzamiento BETWEEN 1900 AND 2100),
    CONSTRAINT ck_cont_duracion CHECK (duracion_minutos > 0),
    CONSTRAINT ck_cont_edad CHECK (clasificacion_edad IN ('TP', '+7', '+13', '+16', '+18')),
    CONSTRAINT ck_cont_original CHECK (es_original IN ('S', 'N')),
    CONSTRAINT ck_cont_estado CHECK (estado_publicacion IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE contenido_genero (
    id_contenido         NUMBER NOT NULL,
    id_genero            NUMBER NOT NULL,
    CONSTRAINT pk_contenido_genero PRIMARY KEY (id_contenido, id_genero),
    CONSTRAINT fk_cg_contenido FOREIGN KEY (id_contenido) REFERENCES contenido(id_contenido),
    CONSTRAINT fk_cg_genero FOREIGN KEY (id_genero) REFERENCES generos(id_genero)
);

CREATE TABLE temporadas (
    id_temporada         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_contenido         NUMBER         NOT NULL,
    numero_temporada     NUMBER(3)      NOT NULL,
    titulo_temporada     VARCHAR2(120)  NOT NULL,
    fecha_lanzamiento    DATE,
    CONSTRAINT pk_temporadas PRIMARY KEY (id_temporada),
    CONSTRAINT uq_temporadas UNIQUE (id_contenido, numero_temporada),
    CONSTRAINT fk_temporadas_contenido FOREIGN KEY (id_contenido) REFERENCES contenido(id_contenido),
    CONSTRAINT ck_temporadas_num CHECK (numero_temporada > 0)
);

CREATE TABLE episodios (
    id_episodio          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_temporada         NUMBER         NOT NULL,
    numero_episodio      NUMBER(4)      NOT NULL,
    titulo_episodio      VARCHAR2(150)  NOT NULL,
    duracion_minutos     NUMBER(6)      NOT NULL,
    fecha_publicacion    DATE,
    CONSTRAINT pk_episodios PRIMARY KEY (id_episodio),
    CONSTRAINT uq_episodios UNIQUE (id_temporada, numero_episodio),
    CONSTRAINT fk_episodios_temporada FOREIGN KEY (id_temporada) REFERENCES temporadas(id_temporada),
    CONSTRAINT ck_episodios_num CHECK (numero_episodio > 0),
    CONSTRAINT ck_episodios_duracion CHECK (duracion_minutos > 0)
);

CREATE TABLE contenido_relacionado (
    id_contenido_origen  NUMBER         NOT NULL,
    id_contenido_destino NUMBER         NOT NULL,
    tipo_relacion        VARCHAR2(30)   NOT NULL,
    descripcion          VARCHAR2(200),
    CONSTRAINT pk_contenido_rel PRIMARY KEY (id_contenido_origen, id_contenido_destino, tipo_relacion),
    CONSTRAINT fk_cr_origen FOREIGN KEY (id_contenido_origen) REFERENCES contenido(id_contenido),
    CONSTRAINT fk_cr_destino FOREIGN KEY (id_contenido_destino) REFERENCES contenido(id_contenido),
    CONSTRAINT ck_cr_tipo CHECK (tipo_relacion IN ('SECUELA', 'PRECUELA', 'REMAKE', 'SPIN_OFF', 'VERSION_EXTENDIDA', 'RELACIONADO')),
    CONSTRAINT ck_cr_distinto CHECK (id_contenido_origen <> id_contenido_destino)
);

CREATE TABLE pagos (
    id_pago              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario           NUMBER         NOT NULL,
    id_plan              NUMBER         NOT NULL,
    fecha_pago           DATE           NOT NULL,
    fecha_vencimiento    DATE           NOT NULL,
    monto_base           NUMBER(10,2)   NOT NULL,
    valor_descuento      NUMBER(10,2)   DEFAULT 0 NOT NULL,
    monto_pagado         NUMBER(10,2)   NOT NULL,
    metodo_pago          VARCHAR2(20)   NOT NULL,
    estado_pago          VARCHAR2(15)   NOT NULL,
    observacion          VARCHAR2(200),
    CONSTRAINT pk_pagos PRIMARY KEY (id_pago),
    CONSTRAINT fk_pagos_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_pagos_plan FOREIGN KEY (id_plan) REFERENCES planes(id_plan),
    CONSTRAINT ck_pagos_mbase CHECK (monto_base >= 0),
    CONSTRAINT ck_pagos_vdesc CHECK (valor_descuento >= 0),
    CONSTRAINT ck_pagos_mpagado CHECK (monto_pagado >= 0),
    CONSTRAINT ck_pagos_metodo CHECK (metodo_pago IN ('TCREDITO', 'TDEBITO', 'PSE', 'NEQUI', 'DAVIPLATA')),
    CONSTRAINT ck_pagos_estado CHECK (estado_pago IN ('EXITOSO', 'FALLIDO', 'PENDIENTE', 'REEMBOLSADO'))
);

CREATE TABLE reproducciones (
    id_reproduccion      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_perfil            NUMBER         NOT NULL,
    id_contenido         NUMBER         NOT NULL,
    id_episodio          NUMBER,
    fecha_hora_inicio    TIMESTAMP      NOT NULL,
    fecha_hora_fin       TIMESTAMP,
    dispositivo          VARCHAR2(20)   NOT NULL,
    porcentaje_avance    NUMBER(5,2)    DEFAULT 0 NOT NULL,
    CONSTRAINT pk_reproducciones PRIMARY KEY (id_reproduccion),
    CONSTRAINT fk_rep_perfil FOREIGN KEY (id_perfil) REFERENCES perfiles(id_perfil),
    CONSTRAINT fk_rep_contenido FOREIGN KEY (id_contenido) REFERENCES contenido(id_contenido),
    CONSTRAINT fk_rep_episodio FOREIGN KEY (id_episodio) REFERENCES episodios(id_episodio),
    CONSTRAINT ck_rep_dispositivo CHECK (dispositivo IN ('CELULAR', 'TABLET', 'TV', 'COMPUTADOR')),
    CONSTRAINT ck_rep_avance CHECK (porcentaje_avance BETWEEN 0 AND 100),
    CONSTRAINT ck_rep_fechas CHECK (fecha_hora_fin IS NULL OR fecha_hora_fin >= fecha_hora_inicio)
)
PARTITION BY RANGE (fecha_hora_inicio)
(
    PARTITION p_repro_2024 VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00'),
    PARTITION p_repro_2025 VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00'),
    PARTITION p_repro_max  VALUES LESS THAN (MAXVALUE)
);

CREATE TABLE calificaciones (
    id_calificacion      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_perfil            NUMBER         NOT NULL,
    id_contenido         NUMBER         NOT NULL,
    estrellas            NUMBER(1)      NOT NULL,
    resena               VARCHAR2(1000),
    fecha_calificacion   DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    CONSTRAINT pk_calificaciones PRIMARY KEY (id_calificacion),
    CONSTRAINT uq_calif_perfil_contenido UNIQUE (id_perfil, id_contenido),
    CONSTRAINT fk_calif_perfil FOREIGN KEY (id_perfil) REFERENCES perfiles(id_perfil),
    CONSTRAINT fk_calif_contenido FOREIGN KEY (id_contenido) REFERENCES contenido(id_contenido),
    CONSTRAINT ck_calif_estrellas CHECK (estrellas BETWEEN 1 AND 5)
);

CREATE TABLE favoritos (
    id_perfil            NUMBER         NOT NULL,
    id_contenido         NUMBER         NOT NULL,
    fecha_agregado       DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    CONSTRAINT pk_favoritos PRIMARY KEY (id_perfil, id_contenido),
    CONSTRAINT fk_fav_perfil FOREIGN KEY (id_perfil) REFERENCES perfiles(id_perfil),
    CONSTRAINT fk_fav_contenido FOREIGN KEY (id_contenido) REFERENCES contenido(id_contenido)
);

CREATE TABLE reportes_contenido (
    id_reporte           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario_reporta   NUMBER         NOT NULL,
    id_contenido         NUMBER         NOT NULL,
    id_usuario_moderador NUMBER,
    fecha_reporte        DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    motivo               VARCHAR2(200)  NOT NULL,
    estado_reporte       VARCHAR2(15)   DEFAULT 'PENDIENTE' NOT NULL,
    fecha_resolucion     DATE,
    decision_moderacion  VARCHAR2(200),
    CONSTRAINT pk_reportes PRIMARY KEY (id_reporte),
    CONSTRAINT fk_reporta_usuario FOREIGN KEY (id_usuario_reporta) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_reporta_contenido FOREIGN KEY (id_contenido) REFERENCES contenido(id_contenido),
    CONSTRAINT fk_reporta_moderador FOREIGN KEY (id_usuario_moderador) REFERENCES usuarios(id_usuario),
    CONSTRAINT ck_reportes_estado CHECK (estado_reporte IN ('PENDIENTE', 'EN_REVISION', 'RESUELTO', 'RECHAZADO'))
);

PROMPT =====================================================
PROMPT COMENTARIOS DE TABLAS
PROMPT =====================================================

COMMENT ON TABLE planes IS 'Catalogo de planes de suscripcion disponibles en QuindioFlix.';
COMMENT ON COLUMN planes.id_plan IS 'Clave primaria del plan.';
COMMENT ON COLUMN planes.nombre_plan IS 'Nombre comercial del plan.';
COMMENT ON COLUMN planes.precio_mensual IS 'Valor base mensual del plan.';
COMMENT ON COLUMN planes.max_pantallas IS 'Numero maximo de pantallas simultaneas.';
COMMENT ON COLUMN planes.calidad_video IS 'Calidad maxima de reproduccion.';
COMMENT ON COLUMN planes.max_perfiles IS 'Numero maximo de perfiles permitidos.';
COMMENT ON COLUMN planes.descripcion IS 'Descripcion funcional del plan.';

COMMENT ON TABLE departamentos IS 'Departamentos internos del equipo de trabajo de QuindioFlix.';
COMMENT ON COLUMN departamentos.id_departamento IS 'Clave primaria del departamento.';
COMMENT ON COLUMN departamentos.nombre_departamento IS 'Nombre del departamento.';
COMMENT ON COLUMN departamentos.descripcion IS 'Descripcion del objetivo del departamento.';
COMMENT ON COLUMN departamentos.id_jefe IS 'Empleado que actua como jefe del departamento.';

COMMENT ON TABLE empleados IS 'Empleados de QuindioFlix organizados por departamento.';
COMMENT ON COLUMN empleados.id_empleado IS 'Clave primaria del empleado.';
COMMENT ON COLUMN empleados.id_departamento IS 'Departamento al que pertenece el empleado.';
COMMENT ON COLUMN empleados.supervisor_id IS 'Supervisor directo del empleado.';
COMMENT ON COLUMN empleados.nombres IS 'Nombres del empleado.';
COMMENT ON COLUMN empleados.apellidos IS 'Apellidos del empleado.';
COMMENT ON COLUMN empleados.correo IS 'Correo corporativo unico.';
COMMENT ON COLUMN empleados.telefono IS 'Telefono de contacto.';
COMMENT ON COLUMN empleados.cargo IS 'Cargo que ocupa en la organizacion.';
COMMENT ON COLUMN empleados.fecha_ingreso IS 'Fecha de ingreso a la compania.';
COMMENT ON COLUMN empleados.salario IS 'Salario mensual del empleado.';
COMMENT ON COLUMN empleados.estado_empleado IS 'Estado laboral del empleado.';

COMMENT ON TABLE usuarios IS 'Cuentas de usuario registradas en la plataforma.';
COMMENT ON COLUMN usuarios.id_usuario IS 'Clave primaria del usuario.';
COMMENT ON COLUMN usuarios.id_plan_actual IS 'Plan de suscripcion vigente del usuario.';
COMMENT ON COLUMN usuarios.id_usuario_referidor IS 'Usuario que refirio al usuario actual.';
COMMENT ON COLUMN usuarios.nombres IS 'Nombres del usuario.';
COMMENT ON COLUMN usuarios.apellidos IS 'Apellidos del usuario.';
COMMENT ON COLUMN usuarios.email IS 'Correo electronico unico para autenticacion.';
COMMENT ON COLUMN usuarios.telefono IS 'Telefono de contacto del usuario.';
COMMENT ON COLUMN usuarios.fecha_nacimiento IS 'Fecha de nacimiento.';
COMMENT ON COLUMN usuarios.ciudad IS 'Ciudad de residencia.';
COMMENT ON COLUMN usuarios.fecha_registro IS 'Fecha de creacion de la cuenta.';
COMMENT ON COLUMN usuarios.fecha_ultimo_pago IS 'Fecha del ultimo pago exitoso.';
COMMENT ON COLUMN usuarios.fecha_vencimiento IS 'Fecha limite para renovar el servicio.';
COMMENT ON COLUMN usuarios.estado_cuenta IS 'Estado actual de la cuenta.';
COMMENT ON COLUMN usuarios.beneficio_referido IS 'Descripcion del beneficio recibido por referido.';

COMMENT ON TABLE roles_app IS 'Roles funcionales dentro de la aplicacion para usuarios finales.';
COMMENT ON COLUMN roles_app.id_rol_app IS 'Clave primaria del rol de aplicacion.';
COMMENT ON COLUMN roles_app.nombre_rol IS 'Nombre del rol.';
COMMENT ON COLUMN roles_app.descripcion IS 'Descripcion del alcance del rol.';

COMMENT ON TABLE usuario_rol_app IS 'Tabla intermedia para asignar roles de aplicacion a usuarios.';
COMMENT ON COLUMN usuario_rol_app.id_usuario IS 'Usuario al que se le asigna el rol.';
COMMENT ON COLUMN usuario_rol_app.id_rol_app IS 'Rol funcional asignado.';
COMMENT ON COLUMN usuario_rol_app.fecha_asignacion IS 'Fecha de asignacion del rol.';

COMMENT ON TABLE perfiles IS 'Perfiles asociados a una cuenta de usuario.';
COMMENT ON COLUMN perfiles.id_perfil IS 'Clave primaria del perfil.';
COMMENT ON COLUMN perfiles.id_usuario IS 'Cuenta propietaria del perfil.';
COMMENT ON COLUMN perfiles.nombre_perfil IS 'Nombre visible del perfil.';
COMMENT ON COLUMN perfiles.avatar IS 'Ruta o nombre del avatar del perfil.';
COMMENT ON COLUMN perfiles.tipo_perfil IS 'Clasificacion del perfil: adulto o infantil.';
COMMENT ON COLUMN perfiles.fecha_creacion IS 'Fecha de creacion del perfil.';

COMMENT ON TABLE categorias IS 'Categorias principales del catalogo multimedia.';
COMMENT ON COLUMN categorias.id_categoria IS 'Clave primaria de la categoria.';
COMMENT ON COLUMN categorias.nombre_categoria IS 'Nombre de la categoria.';
COMMENT ON COLUMN categorias.descripcion IS 'Descripcion de la categoria.';

COMMENT ON TABLE generos IS 'Generos asociados al contenido del catalogo.';
COMMENT ON COLUMN generos.id_genero IS 'Clave primaria del genero.';
COMMENT ON COLUMN generos.nombre_genero IS 'Nombre del genero.';
COMMENT ON COLUMN generos.descripcion IS 'Descripcion del genero.';

COMMENT ON TABLE contenido IS 'Catalogo general de peliculas, series, documentales, musica y podcasts.';
COMMENT ON COLUMN contenido.id_contenido IS 'Clave primaria del contenido.';
COMMENT ON COLUMN contenido.id_categoria IS 'Categoria principal del contenido.';
COMMENT ON COLUMN contenido.id_empleado_responsable IS 'Empleado del area de contenido responsable de la publicacion.';
COMMENT ON COLUMN contenido.titulo IS 'Titulo comercial del contenido.';
COMMENT ON COLUMN contenido.anio_lanzamiento IS 'Ano de lanzamiento del contenido.';
COMMENT ON COLUMN contenido.duracion_minutos IS 'Duracion total estimada en minutos.';
COMMENT ON COLUMN contenido.sinopsis IS 'Descripcion corta o resumen del contenido.';
COMMENT ON COLUMN contenido.clasificacion_edad IS 'Clasificacion de edad permitida.';
COMMENT ON COLUMN contenido.fecha_agregado_catalogo IS 'Fecha en la que se agrego al catalogo.';
COMMENT ON COLUMN contenido.es_original IS 'Indica si es una produccion original de QuindioFlix.';
COMMENT ON COLUMN contenido.popularidad IS 'Indicador numerico de popularidad del contenido.';
COMMENT ON COLUMN contenido.estado_publicacion IS 'Estado de disponibilidad del contenido.';

COMMENT ON TABLE contenido_genero IS 'Tabla intermedia para la relacion N:M entre contenido y genero.';
COMMENT ON COLUMN contenido_genero.id_contenido IS 'Contenido asociado.';
COMMENT ON COLUMN contenido_genero.id_genero IS 'Genero asociado.';

COMMENT ON TABLE temporadas IS 'Temporadas de series o podcasts.';
COMMENT ON COLUMN temporadas.id_temporada IS 'Clave primaria de la temporada.';
COMMENT ON COLUMN temporadas.id_contenido IS 'Serie o podcast al que pertenece la temporada.';
COMMENT ON COLUMN temporadas.numero_temporada IS 'Numero consecutivo de temporada.';
COMMENT ON COLUMN temporadas.titulo_temporada IS 'Titulo descriptivo de la temporada.';
COMMENT ON COLUMN temporadas.fecha_lanzamiento IS 'Fecha de lanzamiento de la temporada.';

COMMENT ON TABLE episodios IS 'Episodios pertenecientes a una temporada.';
COMMENT ON COLUMN episodios.id_episodio IS 'Clave primaria del episodio.';
COMMENT ON COLUMN episodios.id_temporada IS 'Temporada a la que pertenece el episodio.';
COMMENT ON COLUMN episodios.numero_episodio IS 'Numero consecutivo del episodio.';
COMMENT ON COLUMN episodios.titulo_episodio IS 'Titulo del episodio.';
COMMENT ON COLUMN episodios.duracion_minutos IS 'Duracion en minutos del episodio.';
COMMENT ON COLUMN episodios.fecha_publicacion IS 'Fecha de publicacion del episodio.';

COMMENT ON TABLE contenido_relacionado IS 'Relacion reflexiva entre contenidos del catalogo.';
COMMENT ON COLUMN contenido_relacionado.id_contenido_origen IS 'Contenido origen.';
COMMENT ON COLUMN contenido_relacionado.id_contenido_destino IS 'Contenido destino.';
COMMENT ON COLUMN contenido_relacionado.tipo_relacion IS 'Tipo de relacion entre contenidos.';
COMMENT ON COLUMN contenido_relacionado.descripcion IS 'Detalle adicional de la relacion.';

COMMENT ON TABLE pagos IS 'Historial de pagos mensuales de las cuentas.';
COMMENT ON COLUMN pagos.id_pago IS 'Clave primaria del pago.';
COMMENT ON COLUMN pagos.id_usuario IS 'Usuario que realiza el pago.';
COMMENT ON COLUMN pagos.id_plan IS 'Plan facturado en el pago.';
COMMENT ON COLUMN pagos.fecha_pago IS 'Fecha en la que se registra el pago.';
COMMENT ON COLUMN pagos.fecha_vencimiento IS 'Fecha limite del periodo facturado.';
COMMENT ON COLUMN pagos.monto_base IS 'Monto del plan antes de descuentos.';
COMMENT ON COLUMN pagos.valor_descuento IS 'Valor descontado por beneficios o promociones.';
COMMENT ON COLUMN pagos.monto_pagado IS 'Monto final pagado.';
COMMENT ON COLUMN pagos.metodo_pago IS 'Medio de pago utilizado.';
COMMENT ON COLUMN pagos.estado_pago IS 'Resultado del pago.';
COMMENT ON COLUMN pagos.observacion IS 'Observaciones operativas del pago.';

COMMENT ON TABLE reproducciones IS 'Eventos de reproduccion realizados por perfiles de usuario.';
COMMENT ON COLUMN reproducciones.id_reproduccion IS 'Clave primaria de la reproduccion.';
COMMENT ON COLUMN reproducciones.id_perfil IS 'Perfil que realiza la reproduccion.';
COMMENT ON COLUMN reproducciones.id_contenido IS 'Contenido principal reproducido.';
COMMENT ON COLUMN reproducciones.id_episodio IS 'Episodio reproducido cuando aplica.';
COMMENT ON COLUMN reproducciones.fecha_hora_inicio IS 'Fecha y hora de inicio de la reproduccion.';
COMMENT ON COLUMN reproducciones.fecha_hora_fin IS 'Fecha y hora de finalizacion de la reproduccion.';
COMMENT ON COLUMN reproducciones.dispositivo IS 'Tipo de dispositivo utilizado.';
COMMENT ON COLUMN reproducciones.porcentaje_avance IS 'Porcentaje consumido del contenido.';

COMMENT ON TABLE calificaciones IS 'Valoraciones y resenas dejadas por perfiles.';
COMMENT ON COLUMN calificaciones.id_calificacion IS 'Clave primaria de la calificacion.';
COMMENT ON COLUMN calificaciones.id_perfil IS 'Perfil que califica.';
COMMENT ON COLUMN calificaciones.id_contenido IS 'Contenido calificado.';
COMMENT ON COLUMN calificaciones.estrellas IS 'Numero de estrellas otorgadas.';
COMMENT ON COLUMN calificaciones.resena IS 'Resena escrita opcional.';
COMMENT ON COLUMN calificaciones.fecha_calificacion IS 'Fecha de la calificacion.';

COMMENT ON TABLE favoritos IS 'Lista de favoritos mantenida por cada perfil.';
COMMENT ON COLUMN favoritos.id_perfil IS 'Perfil propietario del favorito.';
COMMENT ON COLUMN favoritos.id_contenido IS 'Contenido marcado como favorito.';
COMMENT ON COLUMN favoritos.fecha_agregado IS 'Fecha de agregacion a favoritos.';

COMMENT ON TABLE reportes_contenido IS 'Reportes de contenido inapropiado enviados por los usuarios.';
COMMENT ON COLUMN reportes_contenido.id_reporte IS 'Clave primaria del reporte.';
COMMENT ON COLUMN reportes_contenido.id_usuario_reporta IS 'Usuario que reporta el contenido.';
COMMENT ON COLUMN reportes_contenido.id_contenido IS 'Contenido reportado.';
COMMENT ON COLUMN reportes_contenido.id_usuario_moderador IS 'Moderador que atiende el reporte.';
COMMENT ON COLUMN reportes_contenido.fecha_reporte IS 'Fecha de creacion del reporte.';
COMMENT ON COLUMN reportes_contenido.motivo IS 'Motivo del reporte.';
COMMENT ON COLUMN reportes_contenido.estado_reporte IS 'Estado operativo del reporte.';
COMMENT ON COLUMN reportes_contenido.fecha_resolucion IS 'Fecha de cierre del reporte.';
COMMENT ON COLUMN reportes_contenido.decision_moderacion IS 'Decision o respuesta del moderador.';

PROMPT =====================================================
PROMPT FIN DEL SCRIPT DE CREACION
PROMPT =====================================================
