DEFINE DATA_DIR = 'C:\app\danie\product\21c\oradata\XE\PROYECTOBD2'

CREATE TABLESPACE ts_repro_2024
DATAFILE '&DATA_DIR\ts_repro_2024.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TABLESPACE ts_repro_2025
DATAFILE '&DATA_DIR\ts_repro_2025.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TABLESPACE ts_repro_max
DATAFILE '&DATA_DIR\ts_repro_max.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

ALTER TABLE reproducciones MOVE PARTITION p_repro_2024 TABLESPACE ts_repro_2024 UPDATE INDEXES;
ALTER TABLE reproducciones MOVE PARTITION p_repro_2025 TABLESPACE ts_repro_2025 UPDATE INDEXES;
ALTER TABLE reproducciones MOVE PARTITION p_repro_max  TABLESPACE ts_repro_max  UPDATE INDEXES;